name: Validate ApexEloquent on Pull Request

on:
  pull_request:
    branches:
      - ci_target

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Create JWT key file
        run: |
          mkdir -p ./assets
          echo "${{ secrets.SF_JWT_KEY }}" > ./assets/server.key

      - name: Authenticate to Dev Hub
        run: |
          sf org login jwt \
            --username ${{ secrets.SF_USERNAME }} \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file assets/server.key \
            --set-default-dev-hub \
            --alias devHub

      - name: Reinstall project in scratch org
        run: make reinstall

      - name: Run all Apex tests
        run: make test

